<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="...">
    <title><?= $data['title'] ?? '' ?></title>

    <!-- Bootstrap core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="css/header.css" rel="stylesheet">

    <?php if(isset($data['extra_css'])): ?>
        <?php foreach($data['extra_css'] as $css): ?>
            <link href="<?= filter_var($css, FILTER_VALIDATE_URL) ? $css : 'css/' . $css ?>" rel="stylesheet">
        <?php endforeach; ?>
    <?php endif; ?>
</head>
