<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="...">
    <title><?= $data['title'] ?></title>

    <!-- Bootstrap core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="css/header.css" rel="stylesheet">
    <link href="css/login.css" rel="stylesheet">
    
    <?php if(isset($data['extra_css'])): ?>
    <link href="css/<?= $data['extra_css']; ?>" rel="stylesheet">
    <?php endif; ?>
</head>

