<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title><?= $data['title'] ?></title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="css/create.css" rel="stylesheet">
        <script src="https://kit.fontawesome.com/69362e78c5.js" crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
        <?php require_once __DIR__ . '/header.phtml'; ?>
    </head> 
    <script>
        $(document).ready(function(){
        $('a[data-bs-toggle="tab"]').on("shown.bs.tab", function(e){
            console.log(e.target); // newly activated tab
            console.log(e.relatedTarget); // previous active tab
            });
        });
    </script>
    <script>
        function bootstrapTabControl(){
            var i, items = $('.nav-link'), pane = $('.tab-pane');
            // next
            $('.nexttab').on('click', function(){
                for(i = 0; i < items.length; i++){
                    if($(items[i]).hasClass('active') == true){
                        break;
                    }
                }
                if(i < items.length - 1){
                    // for tab
                    $(items[i]).removeClass('active');
                    $(items[i+1]).addClass('active');
                    // for pane
                    $(pane[i]).removeClass('show active');
                    $(pane[i+1]).addClass('show active');
                }

        });
        // Prev
        $('.prevtab').on('click', function(){
            for(i = 0; i < items.length; i++){
                if($(items[i]).hasClass('active') == true){
                    break;
                }
            }
            if(i != 0){
                // for tab
                $(items[i]).removeClass('active');
                $(items[i-1]).addClass('active');
                // for pane
                $(pane[i]).removeClass('show active');
                $(pane[i-1]).addClass('show active');
            }
        });
}
bootstrapTabControl();
    </script>
    
    <body>
        <?php
        echo password_hash('guest', PASSWORD_DEFAULT) . PHP_EOL;?>

        <?php if(isset($data['extra_css'])): ?>
            <link href="css/<?= $data['extra_css']; ?>" rel="stylesheet">
        <?php endif; ?>
        <div class="container">

                <?php if(isset($data['record']['id'])): ?>
                    <input type="hidden" name="id" value="<?= $data['record']['id'] ?>" />
                <?php endif; ?>
                <?php if(isset($data['currentPage'])): ?>
                    <input type="hidden" name="page" value="<?= $data['currentPage'] ?>" />
                <?php endif; ?>
                <?php if(isset($data['hash'])): ?>
                    <input type="hidden" name="hash" value="<?= $data['hash'] ?>" />
                <?php endif; ?>

                <ul class="nav nav-tabs">   <!--Using a list to create the tabs -->
                    <li class="nav-item">
                        <a href="#contact-tab" class="nav-link active" data-bs-toggle="tab">Contact Details</a>
                    </li>
                    <li class="nav-item">
                        <a href="#questions-tab" class="nav-link" data-bs-toggle="tab">Questions</a>
                    </li>
                    <li class="nav-item">
                        <a href="#delivery-tab" class="nav-link" data-bs-toggle="tab">Delivery Info</a>
                    </li>
                </ul>
<!-------------------------------------------------------------------------------------------------------------------------------------------------  -->
                <form class="row g-3" action="<?= $data['action'] ?>" method="post">
                    <div class="tab-content">       <!-- This involves the tav content -->
                        <div class="tab-pane fade show active" id="contact-tab">

                            <div class="row">       <!-- start row here -->
                                <h1>Contact & Site Details</h1>
                                <div class="col-md-7">
                                    <label for="site_name" class="form-label">Site Name*</label>
                                    <input type="text"
                                        class="form-control"
                                        id="site_name"
                                        name="site_name"
                                        value="<?= $data['record']['site_name'] ?? '' ?>"
                                        placeholder="Enter Site Name"
                                        required><br>
                                </div>

                                <div class="col-md-5">
                                    <label for="poNum" class="form-label">PO Number*</label>
                                    <input type="text"
                                        class="form-control"
                                        id="poNum"
                                        name="poNum"
                                        value="<?= $data['record']['poNum'] ?? '' ?>"
                                        placeholder="Enter PO Num (Given in Email)"
                                        required>
                                </div>

                                <div class="col-md-5">
                                    <label for="customer_name" class="form-label">Contact Name*</label>
                                    <input type="text"
                                        class="form-control"
                                        id="customer_name"
                                        name="customer_name"
                                        value="<?= $data['record']['customer_name'] ?? '' ?>"
                                        placeholder="Enter Contact Name"
                                        required>
                                </div>
                        
                                <div class="col-md-7">
                                    <label for="customer_email" class="form-label">Email Address*</label>
                                    <input type="email"
                                        class="form-control"
                                        id="customer_email"
                                        name="customer_email"
                                        value="<?= $data['record']['customer_email'] ?? '' ?>"
                                        placeholder="Enter Email"
                                        required>
                                        <br>
                                </div>

                                <div class="col-4">
                                    <label for="customer_mobile" class="form-label">Contact Number*</label>
                                    <input type="tel"
                                        class="form-control"
                                        id="customer_mobile"
                                        name="customer_mobile"
                                        value="<?= $data['record']['customer_mobile'] ?? '' ?>"
                                        placeholder="Enter Contact Number"
                                        required> <br>
                                </div>

                                <div class="col-8">
                                    <label for="street1" class="form-label">Address*</label>
                                    <input type="text"
                                        class="form-control"
                                        id="street1"
                                        name="street1"
                                        value="<?= $data['record']['street1'] ?? '' ?>"
                                        placeholder="Address"
                                        required>
                                </div>

                                <div class="col-md-5">
                                    <label for="city" class="form-label">City/Town*</label>
                                    <input type="text"
                                        class="form-control"
                                        id="city"
                                        name="city"
                                        value="<?= $data['record']['city'] ?? '' ?>"
                                        placeholder="City/Town"
                                        required>
                                </div>

                                <div class="col-md-5">
                                    <label for="county" class="form-label">County</label>
                                    <input type="text"
                                        class="form-control"
                                        id="county"
                                        name="county"
                                        value="<?= $data['record']['county'] ?? '' ?>"
                                        placeholder="County">
                                </div>

                                <div class="col-md-2">
                                    <label for="postcode" class="form-label">Postcode*</label>
                                    <input type="text"
                                        class="form-control"
                                        id="postcode"
                                        name="postcode"
                                        value="<?= $data['record']['postcode'] ?? '' ?>"
                                        placeholder="Postcode"
                                        required> <br>
                                </div>
                            </div>
                        </div>

                        <div class="tab-pane fade" id="questions-tab">
                            <div class="row">
                                <h1>Site Questions</h1>
                                <div class="col-12">
                                    <h6 for="current_machine">1. What is your Current Machine?</h6>
                                        <input type="text"
                                            class="form-control"
                                            id="current_machine"
                                            name="current_machine"
                                            value="<?= $data['record']['current_machine'] ?? '' ?>"
                                            placeholder="Leave blank if none"><br>
                                </div>
                                <div class="col-12">
                                    <h6 for="ordered_machine">2. What Machine did you Order?*</h6>
                                        <input type="text"
                                            class="form-control"
                                            id="ordered_machine"
                                            name="ordered_machine"
                                            value="<?= $data['record']['ordered_machine'] ?? '' ?>"
                                            placeholder="Machine(s) Ordered"
                                            required> <br>
                                </div>
                                <div class="col-12">
                                    <h6 for="q1">3. Are you aware of the Dimensions of the Machine(s) Ordered? 
                                    <a href="img/size-reference.pdf#page=1" target="_blank"><i class="fas fa-question-circle"></i> </a></h6> 
                                    <select class="form-select form-select-sm" name="q1">
                                        <option selected>--Select--</option>
                                        <option value="YES"<?= isset($data['record']['q1']) && $data['record']['q1'] === "YES" ? ' selected' : '' ?>>Yes</option>
                                        <option value="NO"<?= isset($data['record']['q1']) && $data['record']['q1'] === "NO" ? ' selected' : '' ?>>No</option>
                                    </select><br><br>
                                </div>

                                <div class="col-12">
                                    <h6 for="q2">4. Are you aware of the Capacity of the Machine(s) Ordered? 
                                    <a href="img/website-resources.pdf#page=1" target="_blank"><i class="fas fa-question-circle"></i> </a></h6>
                                    <select class="form-select form-select-sm" name="q2">
                                        <option selected>--Select--</option>
                                        <option value="YES"<?= isset($data['record']['q2']) && $data['record']['q2'] === "YES" ? ' selected' : '' ?>>Yes</option>
                                        <option value="NO"<?= isset($data['record']['q2']) && $data['record']['q2'] === "NO" ? ' selected' : '' ?>>No</option>
                                    </select><br><br>
                                </div>
                                <div class="col-12">
                                    <h6 for="q3">5. Are you aware that the Maximum Drain Height is <i>600mm</i> up from the bottom of Machine(s)? 
                                    <a href="img/website-resources.pdf#page=2" target="_blank"><i class="fas fa-question-circle"></i> </a></h6>
                                    <select class="form-select form-select-sm" name="q3">
                                        <option selected>--Select--</option>
                                        <option value="YES"<?= isset($data['record']['q3']) && $data['record']['q3'] === "YES" ? ' selected' : '' ?>>Yes</option>
                                        <option value="NO"<?= isset($data['record']['q3']) && $data['record']['q3'] === "NO" ? ' selected' : '' ?>>No</option>
                                    </select><br><br>
                                </div>
                                <div class="col-12">
                                    <h6 for="q4">6. Are you aware of the Power Supply required for the Machine(s)?
                                    <a href="img/website-resources.pdf#page=3" target="_blank"><i class="fas fa-question-circle"></i> </a></h6>
                                    <select class="form-select form-select-sm" name="q4">
                                        <option selected>--Select--</option>
                                        <option value="YES"<?= isset($data['record']['q4']) && $data['record']['q4'] === "YES" ? ' selected' : '' ?>>Yes</option>
                                        <option value="NO"<?= isset($data['record']['q4']) && $data['record']['q4'] === "NO" ? ' selected' : '' ?>>No</option>
                                    </select><br><br>
                                </div>
                                <div class="col-12">
                                    <h6 for="q5">7. Is there a suitable Water Supply & Waste within <i>1metre</i> of the location?
                                    <a href="img/website-resources.pdf#page=2" target="_blank"><i class="fas fa-question-circle"></i> </a></h6>
                                    <select class="form-select form-select-sm" name="q5">
                                        <option selected>--Select--</option>
                                        <option value="YES"<?= isset($data['record']['q5']) && $data['record']['q5'] === "YES" ? ' selected' : '' ?>>Yes</option>
                                        <option value="NO"<?= isset($data['record']['q5']) && $data['record']['q5'] === "NO" ? ' selected' : '' ?>>No</option>
                                    </select><br><br>
                                </div>
                                <br>
                                <div class="col-12">
                                    <h6 for="q6">8. Is your Site located in a Hard Water area?
                                    <a href="https://www.aquacure.co.uk/knowledge-base/uk-hard-water-map/" target="_blank"><i class="fas fa-question-circle"></i> </a></h6>
                                    <select class="form-select form-select-sm" name="q6">
                                        <option selected>--Select--</option>
                                        <option value="YES"<?= isset($data['record']['q6']) && $data['record']['q6'] === "YES" ? ' selected' : '' ?>>Yes</option>
                                        <option value="NO"<?= isset($data['record']['q6']) && $data['record']['q6'] === "NO" ? ' selected' : '' ?>>No</option>
                                    </select><br>
                                </div>
                            </div>
                        </div>

                        <div class="tab-pane fade" id="delivery-tab">
                            <div class="row">
                                <h1>Site Details</h1>
                                <div class="col-12">
                                    <h6 for="q7">9. What floor is the Machine(s) going to be located on?</h6>
                                        <input type="text"
                                            class="form-control"
                                            id="q7"
                                            name="q7"
                                            value="<?= $data['record']['q7'] ?? '' ?>"
                                            placeholder="Please enter what floor your machine will be located on"> <br><br>
                                </div>
                                <div class="col-12">
                                    <h6 for="q8">10. Does the Machine Require lifting over a Bar/Countertop?</h6>
                                    <select class="form-select form-select-sm" name="q8">
                                        <option selected>--Select--</option>
                                        <option value="YES"<?= isset($data['record']['q8']) && $data['record']['q8'] === "YES" ? ' selected' : '' ?>>Yes</option>
                                        <option value="NO"<?= isset($data['record']['q8']) && $data['record']['q8'] === "NO" ? ' selected' : '' ?>>No</option>
                                    </select><br><br>
                                </div>
                                <div class="col-12">
                                    <h6 for="q9">11. Is there clear Access to the position of the Machine(s)&nbsp&nbsp&nbsp(e.g. Access through doors)</h6>
                                    <select class="form-select form-select-sm" name="q9">
                                        <option selected>--Select--</option>
                                        <option value="YES"<?= isset($data['record']['q9']) && $data['record']['q9'] === "YES" ? ' selected' : '' ?>>Yes</option>
                                        <option value="NO"<?= isset($data['record']['q9']) && $data['record']['q9'] === "NO" ? ' selected' : '' ?>>No</option>
                                    </select><br><br>
                                </div>
                                <div class="col-12">
                                    <h6 for="q10">12. Are you aware or do you accept that Delivery will be the day <u>before</u> Install and collection of any old machine will be the day <u>after</u> install?</h6>
                                    <select class="form-select form-select-sm" name="q10">
                                        <option selected>--Select--</option>
                                        <option value="YES"<?= isset($data['record']['q10']) && $data['record']['q10'] === "YES" ? ' selected' : '' ?>>Yes</option>
                                        <option value="NO"<?= isset($data['record']['q10']) && $data['record']['q10'] === "NO" ? ' selected' : '' ?>>No</option>
                                    </select><br><br>
                                </div>
                                <div class="col-12">
                                    <h6 for="q11">13. Can you accept Delivery/Install between 8am & 6pm on Weekdays?</h6>
                                    <select class="form-select form-select-sm" name="q11">
                                        <option selected>--Select--</option>
                                        <option value="YES"<?= isset($data['record']['q11']) && $data['record']['q11'] === "YES" ? ' selected' : '' ?>>Yes</option>
                                        <option value="NO"<?= isset($data['record']['q11']) && $data['record']['q11'] === "NO" ? ' selected' : '' ?>>No</option>
                                    </select><br><br>
                                </div>
                                <div class="col-12">
                                    <h6 for="q12">14. Are there any Restrictions on Vehicle Size or Time restrictions in the area? (If Yes, Please Elaborate)</h6>
                                    <input type="text"
                                            class="form-control"
                                            id="q12"
                                            name="q12"
                                            value="<?= $data['record']['q12'] ?? '' ?>"
                                            placeholder="Please enter any restrictions to your site"> 
                                </div>
                                <div class="col-12">
                                <hr>
                                    <h4 for="suggestions">Added Notes / Suggestions</h4>
                                        <input type="text"
                                            class="form-control"
                                            id="suggestions"
                                            name="suggestions"
                                            value="<?= $data['record']['suggestions'] ?? '' ?>"
                                            placeholder="Leave blank if none"><br>
                                </div>
                            </div>
                        </div>
                        
                </div>
            </form>
        </div>
    </body>
<?php require_once __DIR__ . '/footer.phtml'; ?>
