<?php require_once __DIR__ . '/base.phtml'; ?>
<div id="top-bar">
	<nav>
		<div class="top-container">
			<ul class="phone-list">
				<li><a class="phone" href="tel:01889272307">Contact Help: +44 (0)1889272307</a></li> 
			</ul>

			<?php if(isset($_SESSION['username'])): ?>
				
			<ul class="logout-list">
				<li><a>[Logged User -<b> <?= ucfirst($_SESSION['username']) ?>] &nbsp&nbsp</b> </a></li>
				<li><?php if(isset($data['currentPage'])): ?> <a class="backBtn" href="index.php?page=<?= $data['currentPage'] ?>" role="button">Back</a> <?php endif; ?></li>
				<li><a class="logout" href="logout.php">Logout</a></li>
			</ul>
			<?php endif; ?>
		</div>
	</nav>
</div>
